package de.tisan.church.untertitelinator.instancer.packets;

public enum Command {
	JUMP_START, JUMP_END, NEXT_LINE, PREVIOUS_LINE, PAUSE, TOGGLE_UNTERTITEL, TOGGLE_KOLLEKTE, TOGGLE_LOGO, TOGGLE_BEGIN_LAYER, TOGGLE_ENDCARD, CHANGE_SONG, SEND_EVENT, LOAD_SONGS, SELECT_EVENT, LOAD_EVENTS, GET_EVENT_LIST;
}
