package de.tisan.church.untertitelinator.instancer.packets;

public enum Command {
	JUMP_START, JUMP_END, NEXT_LINE, PREVIOUS_LINE, PAUSE, TOGGLE_UNTERTITEL, TOGGLE_KOLLEKTE, TOGGLE_LOGO, TOGGLE_BEGIN_LAYER, TOGGLE_ENDCARD, TOGGLE_PICTURE_ROTATION, CHANGE_SONG, SEND_EVENT, LOAD_SONGS, SELECT_EVENT, LOAD_EVENTS, GET_EVENT_LIST, TOGGLE_VIDEO, SET_VIDEO_FILE, STOP_VIDEO, KEYER_SEND_DISPLAYS, KEYER_CHANGE_DISPLAY, PRESENTATOR_SEND_DISPLAYS, PRESENTATOR_CHANGE_DISPLAY;
}
