package de.tisan.church.untertitelinator.instancer.packets;

public enum Command {
	JUMP_START, JUMP_END, NEXT_LINE, PREVIOUS_LINE, PAUSE, STATE_UNTERTITEL, STATE_KOLLEKTE, STATE_LOGO, STATE_WINDOW_BAR, STATE_BEGIN_CARD, STATE_END_CARD, CHANGE_SONG, SEND_EVENT, LOAD_SONGS, SELECT_EVENT, LOAD_EVENTS;
}
